/*
 * Euler0045
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following
 * formulae:
 *
 * Triangle	 	T(n) = n(n + 1)/2	 	1, 3, 6, 10, 15, ...
 * Pentagonal	 	P(n) = n(3n − 1)/2	 	1, 5, 12, 22, 35, ...
 * Hexagonal	 	H(n) = n(2n − 1)	 	1, 6, 15, 28, 45, ...
 * It can be verified that T(285) = P(165) = H(143) = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 */
package projecteuler;

/**
 *
 * @author Tom
 */
public class Euler0045
{
    public static void solve() {
        int index = 144;
        while (!isPentagonal(getHexagonal(index))) { index++; }
        System.out.println(String.format("%.0f", getHexagonal(index)));
    }
    
    private static boolean isPentagonal(double number) {
        
        int index = (int)((Math.sqrt(24 * number + 1) + 1)/6);
        return index * (3.0 * index - 1) / 2 == number;
    }
    
    private static double getHexagonal(int index) {
        return index * (2.0 * index - 1);
    }
}
