/*
 * Project Euler 0002
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */
package projecteuler;

/**
 *
 * @author Tom
 */
public class Euler0002 {
    public static final int limit = 4000000;
    
    public static void solve() {
        int num1 = 1;
        int num2 = 1;
        int num3;
        int total = 0;
        
        while (num1 + num2 <= limit) {
            num3 = num1 + num2;
            total += num3;
            num1 = num2 + num3;
            num2 = num1 + num3;
        }
        
        System.out.println(String.valueOf(total));
    }
}
